### ISSUE TITLE
Unclear documentation for formula argument of CBMSM

### ISSUE THREAD

**Issue by ngreifer** [kosukeimai/CBPS#18]
The documentation says the argument can be specified as "A list of formulas of the form treat ~ X. The function assumes that there is one formula for each time, and they are ordered from the first time to the last time." However, it seems that only one formula can be entered. It would be nice if the syntax for `CBMSM` was similar to that of `iptw` in `twang` or `weightitMSM` in `WeightIt` so wide datasets could be used (at least as an option). I know this might not be possible given the algorithm used to estimate the weights.

**Comment by ratkovic** [comment]
Noah,

Thank you for your comments.

We have updated the manual to reflect that CBMSM takes a single formula, but the option time.vary controls whether the same coefficients are fit across time (time.vary=FALSE, default) or if these coefficients are fit at each time (time.vary=TRUE).

The function, as written, expects the an (nt) x p matrix, where n is the number of observations in each time, t is the number of time periods, and p the covariates.  Wide datasets will have to be coerced into this form by the user prior to estimation.

Best,

Marc

---------------------------------------------------------------------------------
Marc Ratkovic
Assistant Professor
Department of Politics          Office: 306 Fisher Hall
Princeton University             Email: ratkovic@princeton.edu
Princeton, NJ 08544-1012    http://www.princeton.edu/~ratkovic
---------------------------------------------------------------------------------
________________________________
