### ISSUE TITLE
Problem in hdCBPS

### ISSUE THREAD

**Issue by buutrg** [kosukeimai/CBPS#19]
Hi, with this data, I cannot use hdCBPS to estimate the ATE with this code:
fit = hdCBPS(W ~ MFAP3L + AGR2 + ABCC2, data = all_data, y =y)

it results in the error: 
Error in which(coef(cov1) != 0) : argument to 'which' is not logical

The data is here: https://drive.google.com/file/d/1orNh-3ScT1CKzKuZTcjYTgarzcecEiPc/view?usp=sharing

How can I solve it?
Thanks!

**Comment by psdsam** [comment]
Hi,

Thank you for your interest. We have noticed this problem and the latest
version on Github has this problem fixed. Please use the following command
to download the latest version from Github. We will update the CRAN version
soon.

Please let me know if this solves the problem.

Best,

Sida

## from github
library(devtools)
install_github("kosukeimai/CBPS", dependencies = TRUE)
