### ISSUE TITLE
lines 30-31 in CBPSMain.R is missing argument to function call

### ISSUE THREAD

**Issue by HJ08003** [kosukeimai/CBPS#8]
There is a warning sign on lines 30-31 in CBPSMain.R for "missing argument to function call”

=== lines 30-31 ===
  X <- if (!is.empty.model(mt)) model.matrix(mt, mf)#[,-2]
  else matrix(, NROW(Y), 0L)

**Comment by kosukeimai** [comment]
@christianfong and @ratkovic Do you know what's going on here?  The first argument of `matrix()` is missing

**Comment by HJ08003** [comment]
In the original CBPSMain.R, it is lines 30-31 in CBPSMain.R

**Comment by christianfong** [comment]
Just cleaning up.  matrix() defaults were changed in a recent update to R.  Problem has been resolved.
